integration-test tests basic storage scenario with service keys

diff --git a/jobs/integration-test/templates/bin/cf-create-service b/jobs/integration-test/templates/bin/cf-create-service
--- a/jobs/integration-test/templates/bin/cf-create-service
+++ b/jobs/integration-test/templates/bin/cf-create-service
@@ -1,24 +1,37 @@
 #!/bin/bash
 
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
+
 service=$1
 plan=$2
 name=$3
+service_key=$4
 
-cf create-service $service $plan $name
-cf service $name
+info() {
+  echo "$@ " >&2
+}
+
+cf create-service $service $plan $name >&2
+cf service $name >&2
 
 set +x
 completed_message="Message: Scheduling Completed"
 for ((n=0;n<180;n++)); do
   message=$(cf service $name | grep Message:)
-  echo $message
+  info $message
   if [[ "${message}" == "${completed_message}" ]]; then
     break
   fi
   sleep 1
 done
 if [[ "${message}" != "${completed_message}" ]]; then
-  echo "Failed waiting for service: $status"
+  info "Failed waiting for service: $status"
   exit 1
 fi
 set -x
+
+cf create-service-key $name $service_key >&2
+service_key_guid=$(cf service-key $name $service_key --guid)
+uri=$(cf curl /v2/service_keys/${service_key_guid} | jq -r ".entity.credentials.uri")
+echo $uri
