add -o pipefail to pass thru errors; polling loops have bigger sleeps to make output less noisy

diff --git a/jobs/sanity-test/templates/bin/create-service b/jobs/sanity-test/templates/bin/create-service
--- a/jobs/sanity-test/templates/bin/create-service
+++ b/jobs/sanity-test/templates/bin/create-service
@@ -2,7 +2,7 @@
 
 set -u
 set -e
-set -x
+set -o pipefail
 
 info() {
   echo "$@ " >&2
@@ -13,27 +13,26 @@ create_instance() {
   local plan_id=$2
   local instance_id=$3
   info creating service instance ${instance_id} for plan ${plan_id}
+  set -x
   curl ${BROKER_URI}/v2/service_instances/${instance_id} \
        -XPUT \
-       -d "{\"service_id\": \"${service_id}\", \"plan_id\": \"${plan_id}\"}" \
+       -d "{\"service_id\":\"${service_id}\",\"plan_id\":\"${plan_id}\"}" \
        >&2 || {
     echo "Couldn't create service instance"
     exit 1
   }
   set +x
-  sleep 5
-  for ((n=0;n<120;n++)); do
-      set -x
+  info "Waiting for service instance ${instance_id} to be ready..."
+  sleep 10
+  for ((n=0;n<12;n++)); do
       last_operation=$(curl -s ${BROKER_URI}/v2/service_instances/${instance_id}/last_operation)
-      set +x
-      if echo ${last_operation} | grep 'succeeded' > /dev/null; then
-          set -x
-          return
+      info "$last_operation"
+      if echo "${last_operation}" | grep 'succeeded' > /dev/null; then
+        return
       fi
-      sleep 1
+      sleep 10
   done
-  set -x
-  echo "Couldn't create service instance"
+  echo "Couldn't create service instance within 120s"
   exit 1
 }
 
@@ -43,6 +42,7 @@ create_binding() {
   local instance_id=$3
   local binding_id=$4
   info creating binding ${binding_id} for instance ${instance_id}
+  set -x
   curl -sf ${BROKER_URI}/v2/service_instances/${instance_id}/service_bindings/${binding_id} \
     -XPUT \
     -d "{\"service_id\": \"${service_id}\", \"plan_id\": \"${plan_id}\"}" || {
diff --git a/jobs/sanity-test/templates/bin/test-failure-recovery b/jobs/sanity-test/templates/bin/test-failure-recovery
--- a/jobs/sanity-test/templates/bin/test-failure-recovery
+++ b/jobs/sanity-test/templates/bin/test-failure-recovery
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 set -e
+set -o pipefail
 set -u
 
 service_id=$1
@@ -18,19 +19,19 @@ indent() {
 }
 
 script() {
-  echo *
-  echo *
-  echo * Testing database restoration
-  echo *
-  echo *
+  echo "*"
+  echo "*"
+  echo "* Testing database restoration"
+  echo "*"
+  echo "*"
 
-for ((n=0;n<120;n++)); do
+for ((n=0;n<12;n++)); do
   set -x
   backups_lines=$(curl -sf ${ETCD}/v2/keys/service/${instance_id}/wale-backup-list | jq -r .node.value | wc -l)
   set +x
   if [[ $backups_lines -lt 2 ]]; then
     echo "Waiting for first backups to be written $n"
-    sleep 1
+    sleep 10
   else
     break
   fi
@@ -54,6 +55,11 @@ psql ${uri} -c "select * from sanitytest;"
 echo Deleting service instance
 curl -sf ${BROKER_URI}/v2/service_instances/${instance_id}\?plan_id=${plan_id}\&service_id=${service_id} -XDELETE
 
+if [[ "$(curl -s ${ETCD}/v2/keys/service/${instance_id}/wale-backup-list | jq -r .node.value)" == "null" ]]; then
+  echo "ERROR: No backups available for ${instance_id} after deletion"
+  exit 1
+fi
+
 echo Display wal-e backup status
 curl -s ${ETCD}/v2/keys/service/${instance_id}/wale-backup-list | jq -r .node.value
 
@@ -64,28 +70,56 @@ echo waiting for the cluster to recover
 set +x
 sleep 30
 
+if [[ "$(curl -s ${ETCD}/v2/keys/service/${instance_id}/wale-backup-list | jq -r .node.value)" == "null" ]]; then
+  echo "ERROR: No backups available for ${instance_id} after recovery"
+  exit 1
+fi
 echo Display wal-e backup status
 curl -s ${ETCD}/v2/keys/service/${instance_id}/wale-backup-list | jq -r .node.value
 
-for ((n=0;n<120;n++)); do
-  set -x
+created_ok=false
+for ((n=0;n<30;n++)); do
   last_operation=$(curl ${BROKER_URI}/v2/service_instances/${instance_id}/last_operation)
-  set +x
+  echo $last_operation
   if echo ${last_operation} | grep 'succeeded' > /dev/null; then
-    set -x
+    info final successful state of cluster
+    curl ${BROKER_URI}/admin/service_instances/${instance_id} | jq .
+    created_ok=true
     break
   fi
-  sleep 1
+  sleep 10
 done
 
+if [[ "${created_ok}" == "false" ]]; then
+  echo "Couldn't recreate service instance with 300s"
+  exit 1
+fi
+
 echo "Waiting for haproxy to update and database to restore"
-sleep 31
+set -x
+
+running_ok=false
+for ((n=0;n<6;n++)); do
+  if [ $? -eq 0 ]; then
+    psql ${uri} -c "SELECT current_database();"
+    running_ok=true
+    break
+  fi
+  sleep 10
+done
+if [[ "${running_ok}" == "false" ]]; then
+  echo "Service instance was not running ok after 60s"
+  exit 1
+fi
 
 psql ${uri} -c "SELECT * from sanitytest;"
+
 psql ${uri} -c 'SELECT * FROM sanitytest;' | grep 'test-failure-recovery' || {
   echo Database did not restore
   exit 1
 }
+
+psql ${uri} -c "SELECT pg_is_in_recovery();"
 
 echo Database restored successfully!
 }
diff --git a/jobs/sanity-test/templates/bin/update-service b/jobs/sanity-test/templates/bin/update-service
--- a/jobs/sanity-test/templates/bin/update-service
+++ b/jobs/sanity-test/templates/bin/update-service
@@ -2,6 +2,7 @@
 
 set -u
 set -e
+set -o pipefail
 set -x
 
 info() {
@@ -26,23 +27,22 @@ update_instance() {
     exit 1
   }
   set +x
-  sleep 1
-  for ((n=0;n<300;n++)); do
-      set -x
+  sleep 10
+  for ((n=0;n<30;n++)); do
       last_operation=$(curl -s ${BROKER_URI}/v2/service_instances/${instance_id}/last_operation)
-      set +x
+      echo $last_operation
       if echo ${last_operation} | grep 'succeeded' > /dev/null; then
         info final successful state of cluster
         curl ${BROKER_URI}/admin/service_instances/${instance_id} | jq .
-          return
+        return
       fi
-      sleep 1
+      sleep 0
   done
-  set -x
 
   info final error state of cluster
+  set -x
   curl ${BROKER_URI}/admin/service_instances/${instance_id} | jq .
-  echo "Couldn't update service instance"
+  echo "Couldn't update service instance with 300s"
   exit 1
 }
 
