Use async provisioning

diff --git a/jobs/sanity-test/templates/bin/create-service b/jobs/sanity-test/templates/bin/create-service
--- a/jobs/sanity-test/templates/bin/create-service
+++ b/jobs/sanity-test/templates/bin/create-service
@@ -20,6 +20,20 @@ create_instance() {
     echo "Couldn't create service instance"
     exit 1
   }
+  set +x
+  for ((n=0;n<60;n++)); do
+      set -x
+      last_operation=$(curl  ${BROKER_URI}/v2/service_instances/${instance_id}/last_operation)
+      set +x
+      if echo ${last_operation} | grep 'succeeded'; then
+          set -x
+          return
+      fi
+      sleep 1
+  done
+  set -x
+  echo "Couldn't create service instance"
+  exit 1
 }
 
 create_binding() {
